# Generated by Django 2.1 on 2019-09-21 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0001_initial'),
        ('devices', '0002_auto_20190921_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=5, max_digits=19)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='data.Data')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='devices.Device')),
            ],
        ),
    ]
