# Generated by Django 2.1.7 on 2019-09-22 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='record_time',
        ),
    ]
