# Generated by Django 2.1 on 2019-09-21 16:38

from django.db import migrations


def initial_devices(apps, schema_editor):
    Device = apps.get_model("devices", "Device")
    devices = [
        {
            'code': 'G3112',
            'name': 'Temperature Sensor',
            'unit': '°C',
        },
        {
            'code': 'SCC-525',
            'name': 'Voltage Meter',
            'unit': 'V',
        },
        {
            'code': 'SGB-11233',
            'name': 'Current Meter',
            'unit': '',
        },
        {
            'code': 'SGC-1552',
            'name': 'Power Meter',
            'unit': 'A',
        },
        {
            'code': 'SGD-12344',
            'name': 'Power Meter',
            'unit': 'A',
        },
    ]

    for device in devices:
        Device.objects.create(**device)


def reverse_data(apps, schema_editor):
    Device = apps.get_model("devices", "Device")
    Device.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(initial_devices, reverse_code=reverse_data),
    ]
