# Generated by Django 2.1.7 on 2019-09-22 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20190921_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=254, null=True),
        ),
    ]
